spring.application.name=relationproject
spring.datasource.url=jdbc:mysql://localhost:3306/relation
spring.datasource.username=root
spring.datasource.password=Amzad@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
